language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update -q
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover build/logs/clover.xml
  - vendor/bin/phpcs --standard=PSR2 --extensions=php src tests

after_script:
  - CODECLIMATE_REPO_TOKEN="c64749943f452f321fb2f11676453b71404edd1a36df06ab06c2337d6cbe9980" vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
